name: nexus_fertility_app
description: A fertility tracking app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  audio_session: ^0.1.21
  table_calendar: ^3.0.9
  intl: ^0.20.2
  flutter_gen: ^5.4.0
  email_validator: ^2.1.17
  crypto: ^3.0.3
  path_provider: ^2.1.1
  flutter_local_notifications: ^20.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

dependency_overrides:
  flutter_local_notifications: 20.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#ffffff"
    image: "assets/images/app_logo.png"
    icon_background_color: "#ffffff"

flutter_gen_config:
  output: lib/generated
  line_length: 80
  pubspec_config:
    enabled: true

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/audio/article_1.mp3
    - assets/audio/article_2.mp3
    - assets/audio/article_3.mp3
    - assets/audio/en.mp3
    - assets/audio/ha.mp3
    - assets/audio/pcm.mp3
    - assets/audio/yo.mp3
    - assets/audio/ig.mp3
    - assets/bg.jpeg
    - assets/images/app_logo.png
    - assets/images/article_1.jpeg
    - assets/images/article_2.jpeg
    - assets/images/article_3.jpeg
    - assets/images/pregnant.png
    - assets/icon/
    - assets/icons/
    - assets/splash/
