org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx2G -Xms512m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:GCTimeRatio=9 -XX:InitiatingHeapOccupancyPercent=35
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.build.cache.enabled=true
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=true
# Disable dex-in-process to reduce memory usage
android.dexInProcess=false
# Enable incremental build
org.gradle.incremental=true
