// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1VNI1fON-XfBvFszUTt0oZwHtsgaqcYs',
    appId: '1:293422244200:android:56a4c9785e310e96adb6dd',
    messagingSenderId: '293422244200',
    projectId: 'fertility-app-backend-5578a',
    storageBucket: 'fertility-app-backend-5578a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt_b6mdxXTSk8KaPbeTXq7B6lD9hpATLw',
    appId: '1:293422244200:ios:8cf30e6d907a0f22adb6dd',
    messagingSenderId: '293422244200',
    projectId: 'fertility-app-backend-5578a',
    storageBucket: 'fertility-app-backend-5578a.firebasestorage.app',
    androidClientId: '293422244200-7k52438ana61b6gas9mq4eu5rnhj9k3i.apps.googleusercontent.com',
    iosClientId: '293422244200-tpc624au7p7iprjrdqs975qveka1tlo6.apps.googleusercontent.com',
    iosBundleId: 'com.myfertipall.app',
  );
}
